# Generated by Django 6.0.4 on 2026-04-20 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_paid_event_price_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
